#!/usr/bin/env python

import argparse

from blah.commands import commands

def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()
    
    for command_name, command in commands.iteritems():
        subparser = subparsers.add_parser(command_name)
        subparser.set_defaults(func=command.execute)
        command.create_parser(subparser)
        
    args = parser.parse_args()
    args.func(args)

if __name__ == "__main__":
    main()
