#!/usr/bin/env python

import argparse

from blah.commands import find_command

def main():
    args = parse_args()
    command_name = args.command
    command = find_command(command_name)
    if command is None:
        print 'command not recognised: {0}'.format(command_name)
    else:
        command()

def parse_args():
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('command')
    return parser.parse_args()

if __name__ == "__main__":
    main()
