#!/usr/bin/env python

import sys

from blah.commands import find_command

def main():
    command_name = sys.argv[1]
    command = find_command(command_name)
    if command is None:
        print 'command not recognised: {0}'.format(command_name)
    else:
        command()

if __name__ == "__main__":
    main()
